### ISSUE TITLE
Found a typo that causes index files to never load.

### ISSUE THREAD

**Issue by dogarrowtype** [Vali-98/XTTS-RVC-UI#1]
Hello! Thank you for making this awesome little app, it's very useful!

I noticed that some of my RVC files that worked on other programs, were not producing the expected results on your client. I tracked the issue down to a typo in this line:

https://github.com/Vali-98/XTTS-RVC-UI/blob/11889f71cd44df66561168211a04434b2619e43c/app.py#L102

It should be rvcs, not rvc. Now .index files are loading just fine, and voices sound more accurate.

I don't know how to submit a pull request but I thought this was probably just as good. Thanks again!

**Comment by Vali-98** [comment]
This has been fixed in 0537707bbbf17a536a60c36d174e2f84aba9d040 , thanks for reporting!
