### ISSUE TITLE
Commercial or no?

### ISSUE THREAD

**Issue by Logikschleifen** [Vali-98/XTTS-RVC-UI#14]
I understand that this repo has the MIT license. I just want to double check though, XTTS was licensed by coqui correct? So their non MIT license applies to the output from XTTS?

**Comment by Vali-98** [comment]
Yes, whatever you generate using XTTS is tied to coqui's license.

The MIT License for this repo only encompasses the code used to form the UI, not the model weights nor output of whatever models are used.
