### ISSUE TITLE
Where to find MSVC - VC 2022 C++ x64/x86 build tools?

### ISSUE THREAD

**Issue by Gushousekai195** [Vali-98/XTTS-RVC-UI#3]
Where can I find them so I can get this properly installed?

Edit: Build tools 2022 is not supported on my Windows 10 system. How do I install the UI now?

**Comment by Vali-98** [comment]
You could try the 2019 build tools, granted I myself have not tested this:

https://visualstudio.microsoft.com/visual-cpp-build-tools/

Otherwise, I don't really know any altenatives as the fairseq library is necessary in the project.
